version: "3.9"
services:
  server:
    build: ./server
    ports: 
      - "5000:5000"
    expose:
      - 5000
    volumes: 
    - ./server:/app
    environment: 
      FLASK_ENV: development
  client:
    build: 
      context: ./client/app
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - ./client/app:/user/src/app
    depends_on: 
      - server

  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - 8080:8080
      depends_on:
        - server
        - client